import myLogo from './extensions/logo.png'
import axios from "axios"

const config = {
  head: {
    favicon: myLogo
  },
  translations: {
    en: {
      "Analytics": "آنالیز",
      "Auth.components.Oops.text": "حساب شما مسدود شده است",
      "Auth.components.Oops.text.admin": "اگر اشتباهی رخ داده است، با ادمین تماس بگیرید",
      "Auth.components.Oops.title": "...اوپس",
      "Auth.form.active.label": "فعال سازی",
      "Auth.form.button.forgot-password": "فرستادن ایمیل",
      "Auth.form.button.go-home": "بازگشت به خانه",
      "Auth.form.button.login": "ورود",
      "Auth.form.button.login.providers.error": "نتوانستیم شما را از طریق ارائه کننده انتخابی متصل کینم",
      "Auth.form.button.login.strapi": "ورود با استفاده از استراپی",
      "Auth.form.button.password-recovery": "بازگردانی رمز",
      "Auth.form.button.register": "بیایید شروع کنیم",
      "Auth.form.confirmPassword.label": "تایید رمز",
      "Auth.form.currentPassword.label": "رمز کنونی",
      "Auth.form.email.label": "ایمیل",
      "Auth.form.email.placeholder": "e.g. kai@doe.com",
      "Auth.form.error.blocked": "اکانت شما از طریق ادمین اصلی مسدود شده است",
      "Auth.form.error.code.provide": "کد نادرست است",
      "Auth.form.error.confirmed": "ایمیل شما تایید نشده است",
      "Auth.form.error.email.invalid": "این ایمیل وجود ندارد",
      "Auth.form.error.email.provide": "لطفا نام کاربری یا ایمیل خود را وارد کنید",
      "Auth.form.error.email.taken": "این ایمیل قبلا استفاده شده است",
      "Auth.form.error.invalid": "شناساگر یا رمز نادرست است",
      "Auth.form.error.params.provide": "پارامتر ها نادرست هستند",
      "Auth.form.error.password.format": "شما نمیتواند بیشتر از سه بار از کارکتر '$'در رمز خود استفاده کند",
      "Auth.form.error.password.local": "این کاربر هرگز رمز عبور محلی تنظیم نکرده است، لطفاً از طریق ارائه دهنده استفاده شده در هنگام ایجاد حساب وارد شوید",
      "Auth.form.error.password.matching": "رمز ها مطابقت ندارند",
      "Auth.form.error.password.provide": "لطفا رمز خود را وارد کنید",
      "Auth.form.error.ratelimit": "تعداد تلاش های ناموفق زیاد است، لطفا چند دقیقه دیگر دوباره تلاش نمایید",
      "Auth.form.error.user.not-exist": "این ایمیل موجو خارجی ندارد",
      "Auth.form.error.username.taken": "این نام کاربری قبلا استفاده شده است",
      "Auth.form.firstname.label": "نام",
      "Auth.form.firstname.placeholder": "e.g. Kai",
      "Auth.form.forgot-password.email.label": "ایمیل خود را وارد کنید",
      "Auth.form.forgot-password.email.label.success": "ایمیل با موفقیت ازسال شد به ",
      "Auth.form.lastname.label": "نام خانوادگی",
      "Auth.form.lastname.placeholder": "e.g. Doe",
      "Auth.form.password.hide-password": "پنهان سازی رمز",
      "Auth.form.password.hint": "باید حداقل دارای 8 کارکتر باشد، یک حرف بزرگ، یک حرف کوچک و یک عدد",
      "Auth.form.password.show-password": "نمایش رمز",
      "Auth.form.register.news.label": "من را در مورد ویژگی های جدید و پیشرفت های آینده به روز نگه دار (by doing this you accept the {terms} and the {policy}).",
      "Auth.form.register.subtitle": "اعتبارنامه ها فقط برای احراز هویت در استراپی استفاده می شوند. تمام داده های ذخیره شده در پایگاه داده شما ذخیره می شود",
      "Auth.form.rememberMe.label": "مرا به خاطر بسپار",
      "Auth.form.username.label": "نام کاربری",
      "Auth.form.username.placeholder": "e.g. Kai_Doe",
      "Auth.form.welcome.subtitle": "وارد اکانت استراپی خود شوید",
      "Auth.form.welcome.title": "به استراپی خوش آمدید",
      "Auth.link.forgot-password": "رمز خود را فراموش کردید؟",
      "Auth.link.ready": "آماده ورود هستید؟",
      "Auth.link.signin": "ورود",
      "Auth.link.signin.account": "از قبل اکانت دارید؟",
      "Auth.login.sso.divider": "یا وارد شوید با",
      "Auth.login.sso.loading": "در حال بارگیری ارائه دهندگان...",
      "Auth.login.sso.subtitle": "مورد به حساب کاربری از طریق SSO",
      "Auth.privacy-policy-agreement.policy": "سایست های امنیتی",
      "Auth.privacy-policy-agreement.terms": "شرایط",
      "Auth.reset-password.title": "بازیابی رمز",
      "Content Manager": "مدیریت محتوا",
      "Content Type Builder": "سازنده نوع محتوا ها",
      "Documentation": "مستندات",
      "Email": "ایمیل",
      "Files Upload": "آپلود فایل ها",
      "HomePage.helmet.title": "صفحه خانه",
      "HomePage.roadmap": "دیدن roadmap",
      "HomePage.welcome.congrats": "تبریک میگوییم!",
      "HomePage.welcome.congrats.content": "شما به عنوان اولین مدیر وارد شدید",
      "HomePage.welcome.congrats.content.bold": "پیشنهاد میکنیم اولین نوع مجموعه خود را بسازید",
      "Media Library": "کتابخانه منابع",
      "New entry": "ورودی جدید",
      "Password": "رمز",
      "Provider": "ارائه کننده",
      "ResetPasswordToken": "بازیابی توکن رمز",
      "Role": "Role",
      "Roles & Permissions": "نقش ها و اجازه ها",
      "Roles.ListPage.notification.delete-all-not-allowed": "بعضی از نقش ها به دلیل پیوندشان با کاربران قابل حذف نیستند",
      "Roles.ListPage.notification.delete-not-allowed": "اگر نقش برای کاربر ضروری باشد، قابل حذف نخواهد بود",
      "Roles.RoleRow.select-all": "Select {name} for bulk actions",
      "Roles.RoleRow.user-count": "{number, plural, =0 {# user} one {# user} other {# users}}",
      "Roles.components.List.empty.withSearch": "هیچ نقشی برای پاسخگویی وجود ندارد ({search})...",
      "Settings.PageTitle": "تنظیمات — {name}",
      "Settings.apiTokens.ListView.headers.createdAt": "ساخته شده در",
      "Settings.apiTokens.ListView.headers.description": "توضیحات",
      "Settings.apiTokens.ListView.headers.lastUsedAt": "اخرین بار استفاده شده در ",
      "Settings.apiTokens.ListView.headers.name": "نام",
      "Settings.apiTokens.ListView.headers.type": "نوع توکن",
      "Settings.apiTokens.addFirstToken": "اولین API توکن خود را اضافه کنید",
      "Settings.apiTokens.addNewToken": "افزودن API توکن جدید",
      "Settings.apiTokens.create": "ساخت API توکن جدید",
      "Settings.apiTokens.createPage.BoundRoute.title": "مسیر محدود به",
      "Settings.apiTokens.createPage.permissions.description": "فقط اقدامات محدود شده توسط یک مسیر در زیر فهرست شده است",
      "Settings.apiTokens.createPage.permissions.header.hint": "اقدامات برنامه یا اقدامات افزونه را انتخاب کنید و روی نماد cog کلیک کنید تا مسیر محدود نمایش داده شود.",
      "Settings.apiTokens.createPage.permissions.header.title": "تنظیمات پیشرفته",
      "Settings.apiTokens.createPage.permissions.title": "دسترسی ها",
      "Settings.apiTokens.createPage.title": "ساختن API توکن",
      "Settings.apiTokens.description": "لیست توکن های ایجاد شده برای درخواست API",
      "Settings.apiTokens.emptyStateLayout": "شما هنوز هیچ کانتنتی نساخته اید...",
      "Settings.apiTokens.regenerate": "ساخت دوباره",
      "Settings.apiTokens.title": "API توکن",
      "Settings.apiTokens.lastHour": "اخرین ساعت",
      "Settings.application.customization": "شخصی سازی",
      "Settings.application.customization.auth-logo.carousel-hint": "عوض کردن لوگو صفحه اول",
      "Settings.application.customization.carousel-hint": "تغییر لوگو پنل ادمین (Max dimension: {dimension}x{dimension}, Max file size: {size}KB)",
      "Settings.application.customization.carousel-slide.label": "اسلاید لوگو",
      "Settings.application.customization.carousel.auth-logo.title": "آرم احراز هویت",
      "Settings.application.customization.carousel.change-action": "تغییر لوگو",
      "Settings.application.customization.carousel.menu-logo.title": "منو لوگو",
      "Settings.application.customization.carousel.reset-action": "بازگردانی لوگو",
      "Settings.application.customization.carousel.title": "لوگو",
      "Settings.application.customization.menu-logo.carousel-hint": "تغییر لوگو در نوار جهت یابی اصلی",
      "Settings.application.customization.modal.cancel": "لغوکردن",
      "Settings.application.customization.modal.pending": "لوگوی معلق",
      "Settings.application.customization.modal.pending.card-badge": "عکس",
      "Settings.application.customization.modal.pending.choose-another": "انتخاب یک لوگو دیگر",
      "Settings.application.customization.modal.pending.subtitle": "تغییر لوگو انتخابی قبل از قرار دادن آن",
      "Settings.application.customization.modal.pending.title": "لوگو آماده آپلود است",
      "Settings.application.customization.modal.pending.upload": "آپلود لوگو",
      "Settings.application.customization.modal.tab.label": "چگونه می خواهید دارایی های خود را آپلود کنید؟",
      "Settings.application.customization.modal.upload": "بروزرسانی لوگو",
      "Settings.application.customization.modal.upload.cta.browse": "پیدا کردن فایل",
      "Settings.application.customization.modal.upload.drag-drop": "بکشید و اینحا بیندازید یا",
      "Settings.application.customization.modal.upload.error-format": "فرمت آپلود قابل قبول نیست (فرمت های قابل قبول: jpeg, jpg, png, svg).",
      "Settings.application.customization.modal.upload.error-network": "خطای اینترنت",
      "Settings.application.customization.modal.upload.error-size": "فایل آپلود شده بزرگ است (max dimension: {dimension}x{dimension}, max file size: {size}KB)",
      "Settings.application.customization.modal.upload.file-validation": "Max dimension: {dimension}x{dimension}, Max size: {size}KB",
      "Settings.application.customization.modal.upload.from-computer": "از کامپیوتر",
      "Settings.application.customization.modal.upload.from-url": "از URL",
      "Settings.application.customization.modal.upload.from-url.input-label": "URL",
      "Settings.application.customization.modal.upload.next": "بعدی",
      "Settings.application.customization.size-details": "Max dimension: {dimension}×{dimension}, Max file size: {size}KB",
      "Settings.application.description": "اطلاعات جهانی پنل مدیریت",
      "Settings.application.edition-title": "نقشه کنونی",
      "Settings.application.ee-or-ce": "{communityEdition, select, true {Community Edition} other {Enterprise Edition}}",
      "Settings.application.ee.admin-seats.add-seats": "{isHostedOnStrapiCloud, select, true {Add seats} other {Contact sales}}",
      "Settings.application.ee.admin-seats.at-limit-tooltip": "در نسخه محدود: برای دعوت از کاربران بیشتر، صندلی اضافه کنید",
      "Settings.application.ee.admin-seats.count": "<text>{enforcementUserCount}</text>/{permittedSeats}",
      "Settings.application.get-help": "راهنمایی",
      "Settings.application.link-pricing": "مشاهده همه طرح های قیمت گذاری",
      "Settings.application.link-upgrade": "ارتقا پنل ادمین",
      "Settings.application.node-version": "ورژن node",
      "Settings.application.strapi-version": "Strapi ورژن",
      "Settings.application.strapiVersion": "Strapi ورژن",
      "Settings.application.title": "بررسی اجمالی",
      "Settings.error": "ارور",
      "Settings.global": "تنظیمات جهانی",
      "Settings.permissions": "پنل مدیریت",
      "Settings.permissions.auditLogs.action": "عمل",
      "Settings.permissions.auditLogs.admin.auth.success": "ورود ادمین",
      "Settings.permissions.auditLogs.admin.logout": "خروج ادمین",
      "Settings.permissions.auditLogs.component.create": "ساخت کامپوننت",
      "Settings.permissions.auditLogs.component.delete": "حذف کامپوننت",
      "Settings.permissions.auditLogs.component.update": "بروز رسانی کامپوننت",
      "Settings.permissions.auditLogs.content-type.create": "ساخت نوع داده",
      "Settings.permissions.auditLogs.content-type.delete": "حذف نوع داده",
      "Settings.permissions.auditLogs.content-type.update": "بروز رسانی نوع داده",
      "Settings.permissions.auditLogs.date": "تاریخ",
      "Settings.permissions.auditLogs.details": "Log Details",
      "Settings.permissions.auditLogs.entry.create": "ساخت ورودی{model, select, undefined {} other { ({model})}}",
      "Settings.permissions.auditLogs.entry.delete": "حذف ورودی{model, select, undefined {} other { ({model})}}",
      "Settings.permissions.auditLogs.entry.publish": "انتشار ورودی {model, select, undefined {} other {({model})}}",
      "Settings.permissions.auditLogs.entry.unpublish": "لغو انتشار ورودی{model, select, undefined {} other { ({model})}}",
      "Settings.permissions.auditLogs.entry.update": "بروز رسانی ورودی{model, select, undefined {} other { ({model})}}",
      "Settings.permissions.auditLogs.filters.combobox.aria-label": "جستوجو و انتخاب یک مورد برای فیلتر کردن",
      "Settings.permissions.auditLogs.listview.header.subtitle": "گزارش تمام فعالیت هایی که در محیط شما اتفاق افتاده است",
      "Settings.permissions.auditLogs.media.create": "ساخت رسانه",
      "Settings.permissions.auditLogs.media.delete": "حذف رسانه",
      "Settings.permissions.auditLogs.media.update": "بروز رسانی رسانه",
      "Settings.permissions.auditLogs.payload": "Payload",
      "Settings.permissions.auditLogs.permission.create": "ساخت اجازه",
      "Settings.permissions.auditLogs.permission.delete": "حذف اجازه",
      "Settings.permissions.auditLogs.permission.update": "بروز رسانی اجازه ",
      "Settings.permissions.auditLogs.role.create": "ساخت نقش",
      "Settings.permissions.auditLogs.role.delete": "حذف نقش",
      "Settings.permissions.auditLogs.role.update": "بروز رسانی تقش",
      "Settings.permissions.auditLogs.user": "کاربر",
      "Settings.permissions.auditLogs.user.create": "ساخت کاربر",
      "Settings.permissions.auditLogs.user.delete": "حذف کاربر",
      "Settings.permissions.auditLogs.user.fullname": "{نام} {نام خانوادگی}",
      "Settings.permissions.auditLogs.user.update": "بروز رسانی کاربر",
      "Settings.permissions.auditLogs.userId": "ID کاربر",
      "Settings.permissions.category": "تنظیمات اجازه ها برای {کتگوری ها}",
      "Settings.permissions.category.plugins": "تنظیمات دسترسی برای {category} ",
      "Settings.permissions.conditions.anytime": "هر زمان",
      "Settings.permissions.conditions.apply": "افزودن",
      "Settings.permissions.conditions.can": "میتواند",
      "Settings.permissions.conditions.conditions": "شرایط",
      "Settings.permissions.conditions.define-conditions": "تعریف شرایط",
      "Settings.permissions.conditions.links": "لینک ها",
      "Settings.permissions.conditions.no-actions": "اول باید عمل را انتخاب کنید (create, read, update, ...) before defining conditions on them.",
      "Settings.permissions.conditions.none-selected": "هرزمان",
      "Settings.permissions.conditions.or": "یا",
      "Settings.permissions.conditions.when": "چه وقت",
      "Settings.permissions.select-all-by-permission": "انتخاب تمام بخش های اجازه ها {label} ",
      "Settings.permissions.select-by-permission": "انتخاب اجازه ها {label}",
      "Settings.permissions.users.active": "فعال",
      "Settings.permissions.users.create": "دعوت کاربر جدید",
      "Settings.permissions.users.email": "ایمیل",
      "Settings.permissions.users.firstname": "نام",
      "Settings.permissions.users.form.sso": "اتصال به SSO",
      "Settings.permissions.users.sso.provider.error": "هنگام درخواست برای تنظیمات SSO مشکلی پیش آمد",
      "Settings.permissions.users.form.sso.description": "When enabled (ON), users can login via SSO",
      "Settings.permissions.users.inactive": "غیر فعال",
      "Settings.permissions.users.lastname": "نام خانوادگی",
      "Settings.permissions.users.listview.header.subtitle": "تمام کاربرانی که به پنل strapi دستری دارند",
      "Settings.permissions.users.roles": "نقش ها",
      "Settings.permissions.users.strapi-author": "نویسنده",
      "Settings.permissions.users.strapi-editor": "ویرایشگر",
      "Settings.permissions.users.strapi-super-admin": "سوپر ادمین",
      "Settings.permissions.users.tabs.label": "اجازه های برگه ها",
      "Settings.permissions.users.user-status": "وضعیت کاربر",
      "Settings.permissions.users.username": "نام کاربری",
      "Settings.profile.form.notify.data.loaded": "اطلاعات پروفایل شما لود شده است",
      "Settings.profile.form.section.experience.clear.select": "زبان رابط انتخاب شده را پاک کنید",
      "Settings.profile.form.section.experience.here": "اینجا",
      "Settings.profile.form.section.experience.interfaceLanguage": "زبان رابط",
      "Settings.profile.form.section.experience.interfaceLanguage.hint": "این مورد تنهای زبان رابط شما را نشان میدهد",
      "Settings.profile.form.section.experience.interfaceLanguageHelp": "تغییرات اولویت تنها برای شما اعمال میشود. توضیحات بیشتر اینجا {here}.",
      "Settings.profile.form.section.experience.mode.hint": "رابط شما را در حالت انتخابی نمایش می دهد",
      "Settings.profile.form.section.experience.mode.label": "حالت رابط",
      "Settings.profile.form.section.experience.mode.option-label": "{name} مدل",
      "Settings.profile.form.section.experience.title": "تجربه",
      "Settings.profile.form.section.helmet.title": "پروفایل کاربر",
      "Settings.profile.form.section.profile.page.title": "صفحه پروفایل",
      "Settings.review-workflows.page.title": "مشاهده گردش کار",
      "Settings.review-workflows.page.subtitle": "{count, plural, one {# stage} other {# stages}}",
      "Settings.review-workflows.page.isLoading": "در حال لود کردن گردش کار",
      "Settings.review-workflows.page.delete.confirm.body": "تمام ورودی های اختصاص داده شده به مراحل حذف شده به مرحله قبل منتقل می شوند. آیا مطمئن هستید که می خواهید ذخیره کنید؟",
      "Settings.review-workflows.stage.name.label": "نام صحنه",
      "Settings.roles.create.description": "تعریف حقوق هر نقش",
      "Settings.roles.create.title": "ساخت یک نقش",
      "Settings.roles.created": "نقش ساخته شد",
      "Settings.roles.edit.title": "ویرایش نقش",
      "Settings.roles.form.button.users-with-role": "{number, plural, =0 {# users} one {# user} other {# users}} with this role",
      "Settings.roles.form.created": "ساخت",
      "Settings.roles.form.description": "نام و توضیحات نقش",
      "Settings.roles.form.permission.property-label": "{label} اجازه",
      "Settings.roles.form.permissions.attributesPermissions": "بخش های اجازه",
      "Settings.roles.form.permissions.create": "ساخت",
      "Settings.roles.form.permissions.delete": "حذف",
      "Settings.roles.form.permissions.publish": "انتشار",
      "Settings.roles.form.permissions.read": "خواندن",
      "Settings.roles.form.permissions.update": "بروز رسانی",
      "Settings.roles.list.button.add": "افزودن نقش جدید",
      "Settings.roles.list.description": "لیست نقش ها",
      "Settings.roles.title.singular": "نقش",
      "Settings.sso.description": "تنظیمات ویژگی Single Sign-On را پیکربندی کنید.",
      "Settings.sso.form.defaultRole.description": "کاربر تأیید شده جدید را به نقش انتخاب شده متصل می کند",
      "Settings.sso.form.defaultRole.description-not-allowed": "برای خواندن قوانین ادمین به اجازه نیاز دارید",
      "Settings.sso.form.defaultRole.label": "نقش پیشفرض",
      "Settings.sso.form.localAuthenticationLock.label": "قفل احراز هویت محلی",
      "Settings.sso.form.localAuthenticationLock.description": "نقش‌هایی را که می‌خواهید احراز هویت محلی را غیرفعال کنید، انتخاب کنید",
      "Settings.sso.form.registration.description": "در صورت عدم وجود حساب کاربری جدید در ورود به سیستم SSO ایجاد کنید",
      "Settings.sso.form.registration.label": "نام نویسی اتوماتیک",
      "Settings.sso.title": "Single Sign-On",
      "Settings.tokens.Button.cancel": "لغو",
      "Settings.tokens.Button.regenerate": "ساخت دوباره",
      "Settings.tokens.ListView.headers.createdAt": "ساخته شده در ",
      "Settings.tokens.ListView.headers.description": "توضیحات",
      "Settings.tokens.ListView.headers.lastUsedAt": "اخرین بار استفاده شده",
      "Settings.tokens.ListView.headers.name": "نام",
      "Settings.tokens.RegenerateDialog.title": "ساخت دوباره توکن",
      "Settings.tokens.copy.editMessage": "به دلایل امنیتی، شما تنها یک بار میتوانید توکن خود را ببینید",
      "Settings.tokens.copy.editTitle": "این توکن دیگر قابل دسترسی نیست",
      "Settings.tokens.copy.lastWarning": "توکن را حتما کپی کنید، دیگر نمیتوانید آن را ببینید",
      "Settings.tokens.duration.30-days": "30 روز",
      "Settings.tokens.duration.7-days": "7 روز",
      "Settings.tokens.duration.90-days": "90 روز",
      "Settings.tokens.duration.expiration-date": "تاریخ انقضا",
      "Settings.tokens.duration.unlimited": "نامحدود",
      "Settings.tokens.form.description": "توضیحات",
      "Settings.tokens.form.duration": "مدت زمان توکن",
      "Settings.tokens.form.name": "نام",
      "Settings.tokens.form.type": "نوع توکن",
      "Settings.tokens.notification.copied": "توکن در کیبرد ذخیره شد",
      "Settings.tokens.popUpWarning.message": "آیا مطمئن هستید میخواهید این توکن را دوباره ایجاد کنید؟",
      "Settings.tokens.regenerate": "ایجاد دوباره",
      "Settings.tokens.types.custom": "شخصی سازی",
      "Settings.tokens.types.full-access": "دسترسی کامل",
      "Settings.tokens.types.read-only": "فقط خواندن",
      "Settings.transferTokens.ListView.headers.type": "نوع توکن",
      "Settings.transferTokens.addFirstToken": "اولین توکن انتقال خود را اضافه کنید",
      "Settings.transferTokens.addNewToken": "افزودن توکن انتقال جدید",
      "Settings.transferTokens.create": "ساخت توکن انتقال جدید",
      "Settings.transferTokens.createPage.title": "ساخت توکن انتقال",
      "Settings.transferTokens.description": "لیست توکن های انتقال ساخته شده",
      "Settings.transferTokens.emptyStateLayout": "هنوز هیچ کانتنتی ندارید",
      "Settings.transferTokens.title": "توکن انتقال",
      "Settings.webhooks.create": "ساختن وب هوک",
      "Settings.webhooks.create.header": "ساخت header جدید",
      "Settings.webhooks.created": "وب هوک ساخته شد",
      "Settings.webhooks.event.publish-tooltip": "این رویداد فقط برای محتوایی وجود دارد که سیستم پیش‌نویس/انتشار فعال است",
      "Settings.webhooks.event.select": "انتخاب رویداد",
      "Settings.webhooks.events.isLoading": "در حال لود کردن رویداد ها",
      "Settings.webhooks.events.create": "ساخت",
      "Settings.webhooks.events.update": "بروز رسانی",
      "Settings.webhooks.events.delete": "حذف وب هوک",
      "Settings.webhooks.form.events": "رویداد ها",
      "Settings.webhooks.form.headers": "Headers",
      "Settings.webhooks.form.url": "URL",
      "Settings.webhooks.headers.remove": "حذف سرصفحه شماره {number}",
      "Settings.webhooks.key": "کلید",
      "Settings.webhooks.list.button.add": "ساخت وب هوک جدید",
      "Settings.webhooks.list.description": "Get POST changes notifications",
      "Settings.webhooks.list.empty.description": "وب هوکی پیدا نشد",
      "Settings.webhooks.list.empty.link": "مستندات ما را ببینید",
      "Settings.webhooks.list.empty.title": "هنوز وب هوکی وجود ندارد",
      "Settings.webhooks.list.th.actions": "عمل ها",
      "Settings.webhooks.list.th.status": "وضعیت",
      "Settings.webhooks.list.loading.success": "وب هوک ها لود شدند",
      "Settings.webhooks.singular": "وب هوک",
      "Settings.webhooks.title": "وب هوک ها",
      "Settings.webhooks.to.delete": "{webhooksToDeleteLength, plural, one {# webhook} other {# webhooks}} selected",
      "Settings.webhooks.trigger": "Trigger",
      "Settings.webhooks.trigger.cancel": "Cancel trigger",
      "Settings.webhooks.trigger.pending": "Pending…",
      "Settings.webhooks.trigger.save": "Please save to trigger",
      "Settings.webhooks.trigger.success": "موفقیت آمیز بود!",
      "Settings.webhooks.trigger.success.label": "Trigger succeeded",
      "Settings.webhooks.trigger.test": "Test-trigger",
      "Settings.webhooks.trigger.title": "Save before Trigger",
      "Settings.webhooks.value": "Value",
      "Settings.webhooks.validation.name.required": "نام نیاز است",
      "Settings.webhooks.validation.name.regex": "نام باید با یک حرف شروع شود و از حروف و اعداد و فصله و اندرلاین تشکیل شده باشد",
      "Settings.webhooks.validation.url.required": "Url نیاز است",
      "Settings.webhooks.validation.url.regex": "این مقدار باید یک url موثق باشد",
      "Settings.webhooks.validation.key": "کلید نیاز است",
      "Settings.webhooks.validation.value": "مقدار نیاز است",
      "Usecase.back-end": "بک اند دولوپر",
      "Usecase.button.skip": "رد کردن این سوال",
      "Usecase.content-creator": "Content Creator",
      "Usecase.front-end": "فرانت اند دولوپر",
      "Usecase.full-stack": "فول استک دولوپر",
      "Usecase.input.work-type": "چه کاری را انجام می دهید؟",
      "Usecase.notification.success.project-created": "پروژه با موفقیت ایجاد شد",
      "Usecase.other": "دیگر",
      "Usecase.title": "مقداری درباره خودتان بگویید",
      "Username": "نام",
      "Users & Permissions": "کاربران و اجازه ها",
      "Users": "کاربران",
      "Users.components.List.empty": "کاربری وجود ندارد...",
      "Users.components.List.empty.withFilters": "کاربری با مشخصات گفته شده وجود ندارد",
      "Users.components.List.empty.withSearch": "هیچ کاربری مربوط به جستجو وجود ندارد ({search})...",
      "admin.pages.MarketPlacePage.sort.label": "مرتب سازی با",
      "admin.pages.MarketPlacePage.filters.categories": "کتگوری ها",
      "admin.pages.MarketPlacePage.filters.categoriesSelected": "{count, plural, =0 {No categories} one {# category} other {# categories}} selected",
      "admin.pages.MarketPlacePage.filters.collections": "مجموعه ها",
      "admin.pages.MarketPlacePage.filters.collectionsSelected": "{count, plural, =0 {No Collections} one {# Collection} other {# Collections}} selected",
      "admin.pages.MarketPlacePage.helmet": "Marketplace — Plugins",
      "admin.pages.MarketPlacePage.missingPlugin.description": "به ما بگویید به دنبال چه افزونه ای هستید و در صورتی که در جستجوی الهام باشند به توسعه دهندگان افزونه انجمن خود اطلاع خواهیم داد!",
      "admin.pages.MarketPlacePage.missingPlugin.title": "پلاگینی کم دارید؟",
      "admin.pages.MarketPlacePage.offline.subtitle": "برای دسترسی به فروشگاه strapi باید به اینترنت متصل باشید ",
      "admin.pages.MarketPlacePage.offline.title": "شما آفلاین هستید",
      "admin.pages.MarketPlacePage.plugin.copy": "کپی دستور نصب",
      "admin.pages.MarketPlacePage.plugin.copy.success": "دستور نصب آماده وارد کردن به ترمینال است",
      "admin.pages.MarketPlacePage.plugin.downloads": "This plugin has {downloadsCount} weekly downloads",
      "admin.pages.MarketPlacePage.plugin.githubStars": "This plugin was starred {starsCount} on GitHub",
      "admin.pages.MarketPlacePage.plugin.info": "توضیحات بیشتر ",
      "admin.pages.MarketPlacePage.plugin.info.label": "توضیخات بیشتر در خصوص {pluginName}",
      "admin.pages.MarketPlacePage.plugin.info.text": "بیشتر",
      "admin.pages.MarketPlacePage.plugin.installed": "نصب کامل شد",
      "admin.pages.MarketPlacePage.plugin.tooltip.madeByStrapi": "ساخته شده توسط strapi",
      "admin.pages.MarketPlacePage.plugin.tooltip.verified": "پلاگین های بررسی شده توسط استراپی",
      "admin.pages.MarketPlacePage.plugin.version": "نسخه Strapi خود را به روز کنید: \"{strapiAppVersion}\" to: \"{versionRange}\"",
      "admin.pages.MarketPlacePage.plugin.version.null": "تأیید سازگاری با نسخه Strapi شما امکان پذیر نیست: \"{strapiAppVersion}\"",
      "admin.pages.MarketPlacePage.plugins": "پلاگین ها",
      "admin.pages.MarketPlacePage.provider.downloads": "This provider has {downloadsCount} weekly downloads",
      "admin.pages.MarketPlacePage.provider.githubStars": "This provider was starred {starsCount} on GitHub",
      "admin.pages.MarketPlacePage.providers": "ارائه دهندگان",
      "admin.pages.MarketPlacePage.search.clear": "پاکسازی جستوجو",
      "admin.pages.MarketPlacePage.search.empty": "نتیجه ای یافت نشد \"{target}\"",
      "admin.pages.MarketPlacePage.search.placeholder": "جستوجو",
      "admin.pages.MarketPlacePage.sort.alphabetical": "ترتیب حروف الفبا",
      "admin.pages.MarketPlacePage.sort.alphabetical.selected": "به ترتیب حروف الفبا مرتب سازی کن",
      "admin.pages.MarketPlacePage.sort.githubStars": "تعدا ستاره ها در Github",
      "admin.pages.MarketPlacePage.sort.githubStars.selected": "مرتب سازی بر اساس تعدا ستاره در Github",
      "admin.pages.MarketPlacePage.sort.newest": "جدید ترین",
      "admin.pages.MarketPlacePage.sort.newest.selected": "مرتب سازی بر اساس جدید ترین",
      "admin.pages.MarketPlacePage.sort.npmDownloads": "تعداد دانلود",
      "admin.pages.MarketPlacePage.sort.npmDownloads.selected": "مرتب سازی بر اساس دانلود ها",
      "admin.pages.MarketPlacePage.submit.plugin.link": "ارسال پلاگین",
      "admin.pages.MarketPlacePage.submit.provider.link": "اراسل ارائه دهنده",
      "admin.pages.MarketPlacePage.subtitle": "بیشتر از استراپی بدانید",
      "admin.pages.MarketPlacePage.tab-group.label": "پلاگین ها و ارائه دهندگان برای استراپی",
      "anErrorOccurred": "مشکلی پیش آمد، لطفا دوباره تلاش کنید",
      "app.component.CopyToClipboard.label": "کپی در کیبرد",
      "app.component.search.label": "جستجو برای {target}",
      "app.component.table.duplicate": "تکرار {target}",
      "app.component.table.edit": "ویرایش {target}",
      "app.component.table.read": "خواندن {target}",
      "app.component.table.select.one-entry": "انتخاب {target}",
      "app.component.table.view": "{target} توضیحات",
      "app.components.BlockLink.blog": "وبلاگ",
      "app.components.BlockLink.blog.content": "خواندن آخرین اطلاعات در مورد strapi و ساختار آن",
      "app.components.BlockLink.cloud": "سرویس ابری Strapi",
      "app.components.BlockLink.cloud.content": "یک پلت فرم کاملاً قابل ترکیب و مشارکتی برای افزایش سرعت تیم شما.",
      "app.components.BlockLink.code": "نمونه کد ها",
      "app.components.BlockLink.code.content": "یادگیری با امتحان پروژه های ساخته شده توسط کامیونیتی",
      "app.components.BlockLink.documentation.content": "مفاهیم، راهنماها و دستورالعمل های ضروری را کشف کنید",
      "app.components.BlockLink.tutorial": "آموزش ها",
      "app.components.BlockLink.tutorial.content": "توضیحات قدم به قدم برای شخصی سازی strapi",
      "app.components.Button.cancel": "لغو",
      "app.components.Button.confirm": "تایید",
      "app.components.Button.reset": "بازیابی",
      "app.components.ComingSoonPage.comingSoon": "بزودی اضافه میشود",
      "app.components.ConfirmDialog.title": "تاییدیه",
      "app.components.DownloadInfo.download": "در حال دانلود...",
      "app.components.DownloadInfo.text": "ممکن است مقادی طول بکشد، از صبوری شما متشکریم",
      "app.components.EmptyAttributes.title": "هنوز بخشی وجود ندارد",
      "app.components.EmptyStateLayout.content-document": "چیزی پیدا نشد",
      "app.components.EmptyStateLayout.content-permissions": "شما اجازه دسترسی به این مطلب را ندارید",
      "app.components.GuidedTour.CM.create.content": "<p>در بخش مدیریت محتوا، تمام محتوای خود را بسازید و مدیریت کنید</p><p>مثال: با در نظر گرفتن مثال وب‌سایت بلاگ، می‌توان یک مقاله نوشت، آن را ذخیره و منتشر کرد.</p><p>💡 Quick tip — Don't forget to hit publish on the content you create.</p>",
      "app.components.GuidedTour.CM.create.title": "⚡️ ساخت محتوا",
      "app.components.GuidedTour.CM.success.content": "<p>عالیه، فقط یه بخش دیکه مونده!</p><b>🚀 دیدن مطالب هنگام فال سازی</b>",
      "app.components.GuidedTour.CM.success.cta.title": "تست کردن API",
      "app.components.GuidedTour.CM.success.title": "قدم دوم: کامل شد ✅",
      "app.components.GuidedTour.CTB.create.content": "<p>Collection Types help you manage several entries, Single Types are suitable to manage only one entry.</p> <p>Ex: For a Blog website, Articles would be a Collection Type whereas a Homepage would be a Single Type.</p>",
      "app.components.GuidedTour.CTB.create.cta.title": "ساخت نوع مجموعه",
      "app.components.GuidedTour.CTB.create.title": "🧠 اولین نوع مجموعه خود را بسازید",
      "app.components.GuidedTour.CTB.success.content": "<p>عالی بود!</p><b>⚡️ چه چیز هایی رو میخواهید با دنیا به اشتراک بگذارید؟</b>",
      "app.components.GuidedTour.CTB.success.title": "قدم اول: انجام شد ✅",
      "app.components.GuidedTour.apiTokens.create.content": "<p>در اینجا یک توکن احراز هویت ایجاد کنید و محتوایی را که ایجاد کرده‌اید بازیابی کنید.</p>",
      "app.components.GuidedTour.apiTokens.create.cta.title": "ساخت توکن API",
      "app.components.GuidedTour.apiTokens.create.title": "🚀 محتوای خود را در عمل ببینید",
      "app.components.GuidedTour.apiTokens.success.content": "<p>محتوا را در عمل با استفاده از درخوایت HTTP ببینید:</p><ul><li><p>به این URL: <light>https://'<'YOUR_DOMAIN'>'/api/'<'YOUR_CT'>'</light></p></li><li><p>With the header: <light>Authorization: bearer '<'YOUR_API_TOKEN'>'</light></p></li></ul><p>For more ways to interact with content, see the <documentationLink>documentation</documentationLink>.</p>",
      "app.components.GuidedTour.apiTokens.success.cta.title": "بازگشت به صفحه خانه",
      "app.components.GuidedTour.apiTokens.success.title": "قدم سوم: انجام شد ✅",
      "app.components.GuidedTour.create-content": "ساخت محتوا",
      "app.components.GuidedTour.home.CM.title": "⚡️ چه چیزی را میخواهید با دنیا به اشتراک بگذارید؟",
      "app.components.GuidedTour.home.CTB.cta.title": "برو به سازنده نوع محتوا",
      "app.components.GuidedTour.home.CTB.title": "🧠 ساختار محتوا را بسازید",
      "app.components.GuidedTour.home.apiTokens.cta.title": "امتحان API",
      "app.components.GuidedTour.skip": "رد کردن آموزش",
      "app.components.GuidedTour.title": "3 قدم برای شروع کار",
      "app.components.HomePage.button.blog": "در وبلاگ ما بیشتر بخوانید",
      "app.components.HomePage.community": "عضو شدن در جامعه",
      "app.components.HomePage.community.content": "با اعضای تیم، مشارکت کنندگان و توسعه دهندگان در کانال های مختلف بحث کنید.",
      "app.components.HomePage.create": "اولین نوع محتوای خود را بسازید",
      "app.components.HomePage.roadmap": "دیدن roadmap",
      "app.components.HomePage.welcome": "به صفحه اصلی خوش آمدید 👋",
      "app.components.HomePage.welcome.again": "خوش آمدید 👋",
      "app.components.HomePage.welcomeBlock.content": "تبریک میگم شما به عنوان اولین مدیر وارد سیستم شده اید. برای کشف ویژگی های قدرتمند ارائه شده توسط استراپی، توصیه می کنیم اولین نوع محتوای خود را ایجاد کنید!",
      "app.components.HomePage.welcomeBlock.content.again": "امیدواریم در پروژه خود پیشرفت داشته باشید! با خیال راحت آخرین اخبار استراپی را بخوانید. ما تمام تلاش خود را برای بهبود محصول بر اساس بازخورد شما انجام می دهیم.",
      "app.components.HomePage.welcomeBlock.content.issues": "مشکلات",
      "app.components.HomePage.welcomeBlock.content.raise": " یا بالا رود ",
      "app.components.ImgPreview.hint": "فایل را بکشید و بیاندازید یا جستوجو کنید در مرورگر {browse}",
      "app.components.ImgPreview.hint.browse": "مرورگر",
      "app.components.InputFile.newFile": "افزودن فایل حدید",
      "app.components.InputFileDetails.open": "بازکردن در صفحه جدید",
      "app.components.InputFileDetails.originalName": "نام اصلی:",
      "app.components.InputFileDetails.remove": "حذف این فایل",
      "app.components.InputFileDetails.size": "اندازه:",
      "app.components.InstallPluginPage.Download.description": "دانلود و نصب این پلاگین ممکن است مقداری طول بکشد",
      "app.components.InstallPluginPage.Download.title": "در حال دانلود...",
      "app.components.InstallPluginPage.description": "گسترش برنامه بدون زحمت",
      "app.components.LeftMenu.collapse": "بستن منو جهت یابی",
      "app.components.LeftMenu.expand": "گسترش منو جهت یابی",
      "app.components.LeftMenu.general": "عمومی",
      "app.components.LeftMenu.logo.alt": "لوگو برنامه",
      "app.components.LeftMenu.logout": "خروج",
      "app.components.LeftMenu.navbrand.title": "داشبرد اصلی",
      "app.components.LeftMenu.navbrand.workplace": "کاشی و سرامیک ستاره میبد",// Workplace
      "app.components.LeftMenu.plugins": "پلاگین ها",
      "app.components.LeftMenuFooter.help": "کمک",
      "app.components.LeftMenuFooter.poweredBy": "قدرت گرفته توسط",
      "app.components.LeftMenuLinkContainer.collectionTypes": "اطلاعات پایه",
      "app.components.LeftMenuLinkContainer.configuration": "تبریک میگوییم",
      "app.components.LeftMenuLinkContainer.general": "عمومی",
      "app.components.LeftMenuLinkContainer.noPluginsInstalled": "هنوز پلاگینی نصب نشده است",
      "app.components.LeftMenuLinkContainer.plugins": "پلاگین ها",
      "app.components.LeftMenuLinkContainer.singleTypes": "نوع های تک",
      "app.components.ListPluginsPage.deletePlugin.description": "ممکن است حذف پلاگین ها مقداری طول بکشد",
      "app.components.ListPluginsPage.deletePlugin.title": "در حال حذف",
      "app.components.ListPluginsPage.description": "لیست پلاگین های نصب شده ",
      "app.components.ListPluginsPage.helmet.title": "لیست پلاگین ها",
      "app.components.Logout.logout": "خروج",
      "app.components.Logout.profile": "پروفایل",
      "app.components.MarketplaceBanner": "افزونه های ساخته شده توسط انجمن و بسیاری چیزهای عالی دیگر برای شروع پروژه خود را در مارکت استراپی کشف کنید.",
      "app.components.MarketplaceBanner.image.alt": "آرم موشک استراپی",
      "app.components.MarketplaceBanner.link": "الان ببینید",
      "app.components.NotFoundPage.back": "بازگشت به صفحه خانه",
      "app.components.NotFoundPage.description": "پیدا نشد",
      "app.components.NpsSurvey.banner-title": "چقدر احتمال دارد استراپی را به یک دوست یا همکار توصیه کنید؟",
      "app.components.NpsSurvey.feedback-response": "بابت بازخورد شما سپاس گذاریم!",
      "app.components.NpsSurvey.feedback-question": "ایده ای برای بهبود دارید؟",
      "app.components.NpsSurvey.submit-feedback": "ارسال بازخورد",
      "app.components.NpsSurvey.dismiss-survey-label": "لغو سرویس",
      "app.components.NpsSurvey.no-recommendation": "خیلی کم",
      "app.components.NpsSurvey.happy-to-recommend": "بسیار زیاد",
      "app.components.Official": "رسمی",
      "app.components.Onboarding.help.button": "دکمه های کمکی",
      "app.components.Onboarding.label.completed": "% تکمیل شده",
      "app.components.Onboarding.link.build-content": "یک معماری محتوا بسازید",
      "app.components.Onboarding.link.manage-content": "افزودن و میدریت محتوا",
      "app.components.Onboarding.link.manage-media": "مدیریت رسانه ها",
      "app.components.Onboarding.link.more-videos": "دیده فیلم های بیشتر",
      "app.components.Onboarding.title": "ویدیو های شروع کار",
      "app.components.PluginCard.Button.label.download": "دانلود",
      "app.components.PluginCard.Button.label.install": "قبلا نصب شده است",
      "app.components.PluginCard.PopUpWarning.install.impossible.autoReload.needed": "The autoReload feature needs to be enabled. Please start your app with `yarn develop`.",
      "app.components.PluginCard.PopUpWarning.install.impossible.confirm": "متوجه شدم!",
      "app.components.PluginCard.PopUpWarning.install.impossible.environment": "به دلایل امنیتی، یک پلاگین تنها در سرور توسعه قابل دانلود است",
      "app.components.PluginCard.PopUpWarning.install.impossible.title": "دانلود غیرممکن است",
      "app.components.PluginCard.compatible": "سازگاری با برنامه شما",
      "app.components.PluginCard.compatibleCommunity": "سازگاری با حامعه",
      "app.components.PluginCard.more-details": "جزئیات بیشتر",
      "app.components.ToggleCheckbox.off-label": "خیر",
      "app.components.ToggleCheckbox.on-label": "بله",
      "app.components.Users.MagicLink.connect": "کپی و اشتراک لینک برای دادن دسترسی به کاربر",
      "app.components.Users.MagicLink.connect.sso": "این لینک را برای کاربر ارسال کنید",
      "app.components.Users.ModalCreateBody.block-title.details": "جزئیات کاربر",
      "app.components.Users.ModalCreateBody.block-title.roles": "نقش کاربر",
      "app.components.Users.ModalCreateBody.block-title.roles.description": "یک کاربر میتواند یک یا چند نقش داشته باشد",
      "app.components.Users.SortPicker.button-label": "مرتب سازی با ",
      "app.components.Users.SortPicker.sortby.email_asc": "ایمیل (A to Z)",
      "app.components.Users.SortPicker.sortby.email_desc": "ایمیل (Z to A)",
      "app.components.Users.SortPicker.sortby.firstname_asc": "نام (A to Z)",
      "app.components.Users.SortPicker.sortby.firstname_desc": "نام (Z to A)",
      "app.components.Users.SortPicker.sortby.lastname_asc": "نام خانوادگی (A to Z)",
      "app.components.Users.SortPicker.sortby.lastname_desc": "نام خانوادگی (Z to A)",
      "app.components.Users.SortPicker.sortby.username_asc": "نام کاربری (A to Z)",
      "app.components.Users.SortPicker.sortby.username_desc": "نام کاربری (Z to A)",
      "app.components.listPlugins.button": "افزودن پلاگین جدید",
      "app.components.listPlugins.title.none": "پلاگینی نصب نشده است",
      "app.components.listPluginsPage.deletePlugin.error": "هنگام حذف پلاگین مشکلی رخ داد",
      "app.containers.App.notification.error.init": "در هنگام درخواست API مشکلی رخ داد ",
      "app.containers.AuthPage.ForgotPasswordSuccess.text.contact-admin": "اگر لینک را دریافت نکردید، با ادمین تماس بگیرید",
      "app.containers.AuthPage.ForgotPasswordSuccess.text.email": "ممکن است دریافت لینک برای بازیابی رمز مقداری طول بکشد",
      "app.containers.AuthPage.ForgotPasswordSuccess.title": "ارسال ایمیل",
      "app.containers.Users.EditPage.form.active.label": "فعال ",
      "app.containers.Users.EditPage.header.label": "ویرایش {name}",
      "app.containers.Users.EditPage.header.label-loading": "ویرایش کاربر",
      "app.containers.Users.EditPage.roles-bloc-title": "نقش های نسبت داده شده",
      "app.containers.Users.ModalForm.footer.button-success": "دعوت کاربر",
      "app.links.configure-view": "پیکربندی نما",
      "app.page.not.found": "صفحه ای که دنبالش بودید را پیدا نکردیم ... :(",
      "app.static.links.cheatsheet": "CheatSheet",
      "app.utils.SelectOption.defaultMessage": " ",
      "app.utils.add-filter": "افزودن فیلتر",
      "app.utils.close-label": "بستن",
      "app.utils.defaultMessage": " ",
      "app.utils.delete": "حذف",
      "app.utils.duplicate": "تکرار کردن",
      "app.utils.edit": "ویرایش",
      "app.utils.errors.file-too-big.message": "این فایل زیادی بزرگ است",
      "app.utils.filter-value": "مقادیر فیلتر",
      "app.utils.filters": "فیلتر ها",
      "app.utils.notify.data-loaded": "{target} لود شده است",
      "app.utils.placeholder.defaultMessage": " ",
      "app.utils.publish": "منتشر",
      "app.utils.refresh": "تازه سازی",
      "app.utils.select-all": "انتخاب همه",
      "app.utils.select-field": "انتخاب فیلتر",
      "app.utils.select-filter": "انتخاب فیلتر",
      "app.utils.unpublish": "منتشر نشده",
      "app.utils.published": "منتشر شده",
      "app.utils.ready-to-publish": "آماده انتشار",
      "clearLabel": "پاک کردن",
      "coming.soon": "این بخش در حال حاظر در خال بازسازی است و تا چند هفته دیگر بر میگردد!",
      "component.Input.error.validation.integer": "این مقدار باید اینتیجر باشد",
      "components.AutoReloadBlocker.description": "استراپی را با یکی از دستورات زیر راه اندازی کنید:",
      "components.AutoReloadBlocker.header": "قابلیت بارگیر دوباره برای این افزونه مورد نیاز است.",
      "components.ErrorBoundary.title": "مشکلی پیش آمد...",
      "components.FilterOptions.FILTER_TYPES.$contains": "دربردارنده",
      "components.FilterOptions.FILTER_TYPES.$containsi": "دربردارنده (case insensitive)",
      "components.FilterOptions.FILTER_TYPES.$endsWith": "پایان میابد با",
      "components.FilterOptions.FILTER_TYPES.$endsWithi": "پایان مییابد با (case insensitive)",
      "components.FilterOptions.FILTER_TYPES.$eq": "است",
      "components.FilterOptions.FILTER_TYPES.$eqi": "است (case insensitive)",
      "components.FilterOptions.FILTER_TYPES.$gt": "بزرگتر است از",
      "components.FilterOptions.FILTER_TYPES.$gte": "بزرگتر یا برابر است با",
      "components.FilterOptions.FILTER_TYPES.$lt": "کوچکتر است از",
      "components.FilterOptions.FILTER_TYPES.$lte": "کوچکتر یا برابر است با",
      "components.FilterOptions.FILTER_TYPES.$ne": "نیست",
      "components.FilterOptions.FILTER_TYPES.$nei": "نیست (case insensitive)",
      "components.FilterOptions.FILTER_TYPES.$notContains": "دارای این عبارت نیست",
      "components.FilterOptions.FILTER_TYPES.$notContainsi": "دارای این عبارت نیست (case insensitive)",
      "components.FilterOptions.FILTER_TYPES.$notNull": "نیست null",
      "components.FilterOptions.FILTER_TYPES.$null": "است null",
      "components.FilterOptions.FILTER_TYPES.$startsWith": "آغاز شود با",
      "components.FilterOptions.FILTER_TYPES.$startsWithi": "آغاز شود با (case insensitive)",
      "components.Input.error.attribute.key.taken": "این مقدار از قبل وجود دارد",
      "components.Input.error.attribute.sameKeyAndName": "نمایتوانند برابر باشند",
      "components.Input.error.attribute.taken": "نام این بخش از قبل وجود دارد",
      "components.Input.error.contain.lowercase": "رمز باید حداقل دارای یک حرف کوچک باشد",
      "components.Input.error.contain.number": "رمز باید حداقل دارای یک عدد باشد",
      "components.Input.error.contain.uppercase": "رمز باید حداقل دارای یک حرف بزرگ باشد",
      "components.Input.error.contentTypeName.taken": "این نام از قبل وجود دارد",
      "components.Input.error.custom-error": "{errorMessage} ",
      "components.Input.error.password.noMatch": "رمز ها مطابقط ندارند",
      "components.Input.error.validation.email": "فرمت ایمیل نادرست است",
      "components.Input.error.validation.json": "با فرمت JSON مطابقت ندارد",
      "components.Input.error.validation.lowercase": "این مقدار باید دارای کارکتر های کوچک باشد",
      "components.Input.error.validation.max": "این مقدار زیادی بزرگ است (max: {max}).",
      "components.Input.error.validation.maxLength": "این مقدار زیادی طولانی است (max: {max}).",
      "components.Input.error.validation.min": "این مقداری زیادی کم است (min: {min}).",
      "components.Input.error.validation.minLength": "این مقدار زیادی کوچک است (min: {min}).",
      "components.Input.error.validation.minSupMax": "نمیتواند برتر باشد",
      "components.Input.error.validation.regex": "این مقدار با regex مطابقت ندارد",
      "components.Input.error.validation.required": "این مقدار نیاز است",
      "components.Input.error.validation.unique": "این مقدار قبلا استفاده شده است",
      "components.Input.error.validation.email.withField": "{field} فرمت ایمیل نادرست است",
      "components.Input.error.validation.json.withField": "{field} با فرمت JSON مطابقت ندارد",
      "components.Input.error.validation.lowercase.withField": "{field} باید حروف کوچک باشد",
      "components.Input.error.validation.max.withField": "{field} خیلی بلند است",
      "components.Input.error.validation.maxLength.withField": "{field} خیلی بلند است",
      "components.Input.error.validation.min.withField": "{field} خیلی کم است",
      "components.Input.error.validation.minLength.withField": "{field} خیلی کوتاه است",
      "components.Input.error.validation.minSupMax.withField": "{field} نمیتواند برتر باشد",
      "components.Input.error.validation.regex.withField": "{field} با regex مطابقت ندارد",
      "components.Input.error.validation.required.withField": "{field} نیاز است",
      "components.Input.error.validation.unique.withField": "{field} قبلا استفاده شده است",
      "components.InputSelect.option.placeholder": "اینجا انتخاب کنید",
      "components.ListRow.empty": "داده ای برای نمایش وجود ندارد",
      "components.NotAllowedInput.text": "اجازه برای دیدن این بخش ندارید",
      "components.OverlayBlocker.description": "شما در حال استفاده از بخشی هستید که نیازمند بارگذاری دوباره سرور است، لطفا تا بارگذاری دوباره منتظر بمانید",
      "components.OverlayBlocker.description.serverError": "سرور باید دوباره باگیری شده باشد، لاگ های دورن ترمینال خود را چک کنید",
      "components.OverlayBlocker.title": "در انتظار بارگیری دوباره...",
      "components.OverlayBlocker.title.serverError": "بارگیری دوباره بیشتر از انتظار به طول انجامیده است",
      "components.PageFooter.select": "ورودی ها به ازای صفحه",
      "components.ProductionBlocker.description": "به دلایل امنیتی، ما این پلاگین را در بخش های دیگر غیر فعال کردیم.",
      "components.ProductionBlocker.header": "این بخش فقط در قسمت در حال توسعه موجود است.",
      "components.ViewSettings.tooltip": "مشاهده تنظیمات",
      "components.TableHeader.sort": "مرتب سازی در {label}",
      "components.Blocks.modifiers.bold": "بولد",
      "components.Blocks.modifiers.italic": "ایتالیک",
      "components.Blocks.modifiers.underline": "خط زیر",
      "components.Blocks.modifiers.strikethrough": "ضربه شدن",
      "components.Blocks.modifiers.code": "کد",
      "components.Blocks.blocks.selectBlock": "یک بخش را انتخاب کنید",
      "components.Blocks.blocks.text": "متن",
      "components.Blocks.blocks.heading1": "سر صفحه 1",
      "components.Blocks.blocks.heading2": "سر صفحه 2",
      "components.Blocks.blocks.heading3": "سر صفحه 3",
      "components.Blocks.blocks.heading4": "سر صفحه 4",
      "components.Blocks.blocks.heading5": "سر صفحه 5",
      "components.Blocks.blocks.heading6": "سر صفحه 6",
      "components.Blocks.blocks.quote": "نقل قول",
      "components.Blocks.blocks.image": "عکس",
      "components.Blocks.blocks.unorderedList": "لیست گلوله شده",
      "components.Blocks.blocks.orderedList": "لیست عددی",
      "components.Wysiwyg.ToggleMode.markdown-mode": "حالت علامت گذاری",
      "components.Wysiwyg.ToggleMode.preview-mode": "حالت پیش نمایش",
      "components.Wysiwyg.collapse": "فروپاشی",
      "components.Wysiwyg.selectOptions.H1": "عنوان H1",
      "components.Wysiwyg.selectOptions.H2": "عنوان H2",
      "components.Wysiwyg.selectOptions.H3": "عنوان H3",
      "components.Wysiwyg.selectOptions.H4": "عنوان H4",
      "components.Wysiwyg.selectOptions.H5": "عنوان H5",
      "components.Wysiwyg.selectOptions.H6": "عنوان H6",
      "components.Wysiwyg.selectOptions.title": "افزودن یک عنوان",
      "components.WysiwygBottomControls.charactersIndicators": "کارکتر ها",
      "components.WysiwygBottomControls.fullscreen": "توسعه دادن",
      "components.WysiwygBottomControls.uploadFiles": "فایل ها را بکشید و بیاندازید، از داخل کیرد پیست کنید یا {browse}.",
      "components.WysiwygBottomControls.uploadFiles.browse": "انخابشان کن",
      "components.pagination.go-to": "برو به صفحه {page}",
      "components.pagination.go-to-next": "برو به صفحه بعدی",
      "components.pagination.go-to-previous": "برو به صفحه قبلی",
      "components.pagination.remaining-links": "و {number} لینک دیگر",
      "components.popUpWarning.button.cancel": "خیر، لغو کن",
      "components.popUpWarning.button.confirm": "بله، تایید کن",
      "components.popUpWarning.message": "آیا از حذف این مورد اطمینان دارید؟",
      "components.popUpWarning.title": "لطفا تایید کنید",
      "content-manager.App.schemas.data-loaded": "طرحواره ها با موفقیت بارگیری شدند",
      "content-manager.ListViewTable.relation-loaded": "روابط لود شده اند",
      "content-manager.ListViewTable.relation-loading": "در خال لود کردن روابط",
      "content-manager.ListViewTable.relation-more": "این رابطه دارای موجودیت های بیشتری نسبت به نمایش داده شده است",
      "content-manager.EditRelations.title": "تاریخ رابطه ای",
      "content-manager.HeaderLayout.button.label-add-entry": "ساخت ورودی جدید",
      "content-manager.api.id": "API ID",
      "content-manager.apiError.This attribute must be unique": "{field} باید یکتا باشد",
      "content-manager.components.AddFilterCTA.add": "فیلتر ها",
      "content-manager.components.AddFilterCTA.hide": "فیلتر ها",
      "content-manager.components.DragHandle-label": "کشیدن",
      "content-manager.components.DraggableAttr.edit": "برای ویرایش کلیک کنید",
      "content-manager.components.DraggableCard.delete.field": "حذف {item}",
      "content-manager.components.DraggableCard.edit.field": "ویرایش {item}",
      "content-manager.components.DraggableCard.move.field": "جابه جایی {item}",
      "content-manager.components.ListViewTable.row-line": "خط های مورد {number}",
      "content-manager.components.DynamicZone.ComponentPicker-label": "یک کامپوننت را انتخاب کنید",
      "content-manager.components.DynamicZone.add-component": "کامپوننت را اضافه کنید به {componentName}",
      "content-manager.components.DynamicZone.delete-label": "حذف {name}",
      "content-manager.components.DynamicZone.error-message": "این کامپوننت دارای اررور است",
      "content-manager.components.DynamicZone.missing-components": "اینجا {number, plural, =0 {are # missing components} one {is # missing component} other {are # missing components}}",
      "content-manager.components.DynamicZone.move-down-label": "کاپوننت را پایین ببرید",
      "content-manager.components.DynamicZone.move-up-label": "کامپوننت را بالا ببرید",
      "content-manager.components.DynamicZone.pick-compo": "یک کامپوننت را انتخاب کنید",
      "content-manager.components.DynamicZone.required": "کامپوننت نیاز است",
      "content-manager.components.EmptyAttributesBlock.button": "برو به صفحه تنظیمات",
      "content-manager.components.EmptyAttributesBlock.description": "میتوانید تنظیمات خود را تغییر دهید",
      "content-manager.components.FieldItem.linkToComponentLayout": "افزودن چیدمان کامپوننت خود",
      "content-manager.components.FieldSelect.label": "افزودن یک بخش",
      "content-manager.components.FilterOptions.button.apply": "افزودن",
      "content-manager.components.FiltersPickWrapper.PluginHeader.actions.apply": "افزودن",
      "content-manager.components.FiltersPickWrapper.PluginHeader.actions.clearAll": "پاک کردن همه",
      "content-manager.components.FiltersPickWrapper.PluginHeader.description": "افزودن شرایط برای فیلتر کردن ورودی",
      "content-manager.components.FiltersPickWrapper.PluginHeader.title.filter": "فیلتر ها",
      "content-manager.components.FiltersPickWrapper.hide": "پنهان کردن",
      "content-manager.components.Filters.usersSelect.label": "جست و جو و انتخاب یک کابرای برای فیلتر کردن با ",
      "content-manager.components.LeftMenu.Search.label": "جستجو برای نوع محتوا",
      "content-manager.components.LeftMenu.collection-types": "اطلاعات پایه",
      "content-manager.components.LeftMenu.single-types": "نوع تک موردی",
      "content-manager.components.LimitSelect.itemsPerPage": "عنصر به ازای صفحه",
      "content-manager.components.NotAllowedInput.text": "هیچ مجوزی برای دیدن این بخش وجود ندارد",
      "content-manager.components.RelationInput.icon-button-aria-label": "کشیدن",
      "content-manager.components.RepeatableComponent.error-message": "این کامپوننت دارای اررور است",
      "content-manager.components.Search.placeholder": "جستوجو برای یک ورودی",
      "content-manager.components.Select.draft-info-title": "وضعیت: پیش نویس",
      "content-manager.components.Select.publish-info-title": "وضعیت: منتشر شده",
      "content-manager.components.SettingsViewWrapper.pluginHeader.description.edit-settings": "شخصی سازی نمای ویرایش.",
      "content-manager.components.SettingsViewWrapper.pluginHeader.description.list-settings": "تعریف تنظیمات لیست نمایش",
      "content-manager.components.SettingsViewWrapper.pluginHeader.title": "پیکر بندی نمایش — {name}",
      "content-manager.bulk-publish.already-published": "منتشر شده",
      "content-manager.components.TableDelete.delete": "حذف همه",
      "content-manager.components.TableDelete.deleteSelected": "حذف موارد انتخابی",
      "content-manager.components.TableDelete.label": "{number, plural, one {# entry} other {# entries}} selected",
      "content-manager.components.TableEmpty.withFilters": "There are no {contentType} with the applied filters...",
      "content-manager.components.TableEmpty.withSearch": "There are no {contentType} corresponding to the search ({search})...",
      "content-manager.components.TableEmpty.withoutFilter": "There are no {contentType}...",
      "content-manager.components.empty-repeatable": "ورودی وجود ندارد. روی دکمه پایین برای افزودن ورودی کلیک کنید",
      "content-manager.components.notification.info.maximum-requirement": "شما به سقف بخش های قابل اضافه رسیدید",
      "content-manager.components.notification.info.minimum-requirement": "بخشی اضافه شده تا کمترین مقدار بخش ها را پوشش دهد",
      "content-manager.components.repeatable.reorder.error": "هنگام مرتب کردن مجدد فیلد مؤلفه شما خطایی روی داد، لطفاً دوباره امتحان کنید",
      "content-manager.components.reset-entry": "تنظیم مجدد ورودی",
      "content-manager.components.uid.apply": "افزودن",
      "content-manager.components.uid.available": "موجود",
      "content-manager.components.uid.regenerate": "بازسازی",
      "content-manager.components.uid.suggested": "پیشنهاد شده",
      "content-manager.components.uid.unavailable": "غیرقابل دسترسی",
      "content-manager.containers.Edit.Link.Layout": "پیکربندی چیدمان",
      "content-manager.containers.Edit.Link.Model": "ویرایش  نوع مجموعه ها",
      "content-manager.containers.Edit.addAnItem": "افزودن یک ایتم...",
      "content-manager.containers.Edit.clickToJump": "برای رفتن به این ورودی کلیک کنید",
      "content-manager.containers.Edit.delete": "حذف",
      "content-manager.containers.Edit.delete-entry": "حذف این ورودی",
      "content-manager.containers.Edit.editing": "در حال ویرایش...",
      "content-manager.containers.Edit.information": "اطلاعات",
      "content-manager.containers.Edit.information.by": "توسط",
      "content-manager.containers.Edit.information.created": "ساخته شده",
      "content-manager.containers.Edit.information.draftVersion": "نسخه پیش نویس",
      "content-manager.containers.Edit.information.editing": "در حال ویرایش",
      "content-manager.containers.Edit.information.lastUpdate": "آخرین آپدیت",
      "content-manager.containers.Edit.information.publishedVersion": "ورژن منتشر شده",
      "content-manager.containers.Edit.pluginHeader.title.new": "ساختن یک ورودی",
      "content-manager.containers.Edit.reset": "تنظیم مجدد",
      "content-manager.containers.Edit.returnList": "بازگشت به لیست",
      "content-manager.containers.Edit.seeDetails": "جزئیات",
      "content-manager.containers.Edit.submit": "ذخیره",
      "content-manager.containers.EditSettingsView.modal-form.edit-field": "ویرایش این بخش",
      "content-manager.containers.EditView.add.new-entry": "افزودن ورودی",
      "content-manager.containers.EditView.notification.errors": "فرم دارای چندین اررور است",
      "content-manager.containers.Home.introduction": "برای ویرایش نوشته های خود به پیوند خاص در منوی سمت چپ بروید. این افزونه راه درستی برای ویرایش تنظیمات ندارد و هنوز در حال توسعه فعال است.",
      "content-manager.containers.Home.pluginHeaderDescription": "ورودی های خود را توسط یک رابط قدرتمند و زیبا مدیریت کنید",
      "content-manager.containers.Home.pluginHeaderTitle": "مدیریت محتوا",
      "content-manager.containers.List.draft": "پیش نویش",
      "content-manager.containers.List.errorFetchRecords": "اررور",
      "content-manager.containers.List.published": "منتشر شده",
      "content-manager.containers.ListPage.displayedFields": "بخش های نمایش داده شده",
      "content-manager.containers.ListPage.items": "{number, plural, =0 {items} one {item} other {items}}",
      "content-manager.containers.ListPage.table-headers.publishedAt": "وضعیت",
      "content-manager.containers.ListPage.selectedEntriesModal.title": "منتشر کردن ورودی ها",
      "content-manager.containers.ListPage.selectedEntriesModal.selectedCount": "<b>{alreadyPublishedCount}</b> {alreadyPublishedCount, plural, =0 {entries} one {entry} other {entries}} already published. <b>{readyToPublishCount}</b> {readyToPublishCount, plural, =0 {entries} one {entry} other {entries}} ready to publish. <b>{withErrorsCount}</b> {withErrorsCount, plural, =0 {entries} one {entry} other {entries}} waiting for action.",
      "content-manager.containers.ListPage.selectedEntriesModal.publishedCount": "<b>{publishedCount}</b> {publishedCount, plural, =0 {entries} one {entry} other {entries}} published. <b>{withErrorsCount}</b> {withErrorsCount, plural, =0 {entries} one {entry} other {entries}} waiting for action.",
      "content-manager.containers.ListSettingsView.modal-form.edit-label": "ویرایش {fieldName}",
      "content-manager.containers.SettingPage.add.field": "وارد کردن بخشی دیگر",
      "content-manager.containers.SettingPage.add.relational-field": "وارد کردن بخش ارتباطی دیگر",
      "content-manager.containers.SettingPage.attributes": "بخش های مربوط به ویژگی ها",
      "content-manager.containers.SettingPage.attributes.description": "ترتیب صفات را تعریف کنید",
      "content-manager.containers.SettingPage.editSettings.description": "برای ایجاد طرح بندی، فیلدها را بکشید و بیاندازید",
      "content-manager.containers.SettingPage.editSettings.entry.title": "تیتر ورودی",
      "content-manager.containers.SettingPage.editSettings.entry.title.description": "تنظیم بخش نمایش ورودی ها",
      "content-manager.containers.SettingPage.editSettings.relation-field.description": "فیلد نمایش داده شده را هم در نمای ویرایش و هم در نمای فهرست تنظیم کنید",
      "content-manager.containers.SettingPage.editSettings.title": "ویرایش نوع نمایش (settings)",
      "content-manager.containers.SettingPage.layout": "ساختار",
      "content-manager.containers.SettingPage.listSettings.description": "پیکربندی گزینه های این نوع مجموعه",
      "content-manager.containers.SettingPage.listSettings.title": "نمای لیست (settings)",
      "content-manager.containers.SettingPage.pluginHeaderDescription": "پیکربندی تنظیمات خاص برای نوع مجموعه ها",
      "content-manager.containers.SettingPage.relations": "بخش های مرتبط",
      "content-manager.containers.SettingPage.settings": "تنظیمات",
      "content-manager.containers.SettingPage.view": "مشاهده",
      "content-manager.containers.SettingViewModel.pluginHeader.title": "مدیریت محتوا — {name}",
      "content-manager.containers.SettingsPage.Block.contentType.description": "پیکربندی تنظیمات خاص",
      "content-manager.containers.SettingsPage.Block.contentType.title": "نوع مجموعه ها",
      "content-manager.containers.SettingsPage.Block.generalSettings.description": "پیکربندی پیشفرض برای نوع محتوای شما",
      "content-manager.containers.SettingsPage.Block.generalSettings.title": "عمومی",
      "content-manager.containers.SettingsPage.pluginHeaderDescription": "تنظیمات را برای همه انواع و گروه‌های مجموعه خود پیکربندی کنید",
      "content-manager.containers.SettingsView.list.subtitle": "چیدمان و نمایش انواع و گروه های مجموعه خود را پیکربندی کنید",
      "content-manager.containers.SettingsView.list.title": "نمایش تنظیمات",
      "content-manager.dnd.cancel-item": "{item}, انداختن، مرتب سازی دوباره غیر فعال شد",
      "content-manager.dnd.drop-item": "{item}, انداختن، موقعیت در لیست جدید: {position}.",
      "content-manager.dnd.grab-item": "{item}, grabbed. Current position in list: {position}. Press up and down arrow to change position, Spacebar to drop, Escape to cancel.",
      "content-manager.dnd.instructions": "برای گرفتن و سفارش مجدد، کلید فاصله را فشار دهید",
      "content-manager.dnd.reorder": "{item}, جا به جا شد، موقعیت جدید در لیست: {position}.",
      "content-manager.edit-settings-view.link-to-ctb.components": "ویرایش کامپوننت",
      "content-manager.edit-settings-view.link-to-ctb.content-types": "ویرایش نوع محتوا",
      "content-manager.emptyAttributes.button": "برو به سازنده نوع محتوا",
      "content-manager.emptyAttributes.description": "اولین بخش را به نوع محتوای خود اضافه کنید",
      "content-manager.emptyAttributes.title": "هنوز بخشی وجود ندارد",
      "content-manager.error.attribute.key.taken": "این مقدار قبلا استفاده شده است",
      "content-manager.error.attribute.sameKeyAndName": "نمیتوانند برابر باشند",
      "content-manager.error.attribute.taken": "نام این بخش قبلا استفاده شده است",
      "content-manager.error.contentTypeName.taken": "این نام قبلا استفاده شده است",
      "content-manager.error.model.fetch": "هنگام واکشی پیکربندی مدل ها خطایی روی داد.",
      "content-manager.error.record.create": "هنگام ساخت رکورد ها، مشکلی پیش آمد",
      "content-manager.error.record.delete": "هنگام حذف رکورد ها، مشکلی پیش آمد",
      "content-manager.error.record.fetch": "هنگام دریافت رکورد ها، مشکلی پیش آمد",
      "content-manager.error.record.update": "هنگام بروز رسانی رکورد ها، مشکلی پیش آمد",
      "content-manager.error.records.count": "هنگام گرفتن رکورد ها مشکلی پیش آمد.",
      "content-manager.error.records.fetch": "هنگام دریافت رکورد ها، مشکلی پیش آمد",
      "content-manager.error.schema.generation": "در طول تولید طرحواره خطایی رخ داد.",
      "content-manager.error.validation.json": "این یک JSON نیست",
      "content-manager.error.validation.max": "این عبارت بلند است (max: {max}).",
      "content-manager.error.validation.maxLength": "این عبارت طولانی است (max: {max}).",
      "content-manager.error.validation.min": "این عبارت کوچک است (min: {min}).",
      "content-manager.error.validation.minLength": "این عبارت کوتاه است (min: {min}).",
      "content-manager.error.validation.minSupMax": "نمیتواند برتر باشد",
      "content-manager.error.validation.regex": "این مقدار با regexمطابقت ندارد.",
      "content-manager.error.validation.required": "ورودی برای این بخش الزامی است",
      "content-manager.form.Input.bulkActions": "Enable bulk actions",
      "content-manager.form.Input.defaultSort": "مقادیر مرتب سازی پیش فرض",
      "content-manager.form.Input.description": "توضیحات",
      "content-manager.form.Input.description.placeholder": "نمایش نام در پروفایل",
      "content-manager.form.Input.editable": "بخش های قابل ویرایش",
      "content-manager.form.Input.filters": "فعال سازی فیلتر ها",
      "content-manager.form.Input.hint.character.unit": "{maxValue, plural, one { character} other { characters}}",
      "content-manager.form.Input.hint.minMaxDivider": " / ",
      "content-manager.form.Input.hint.text": "{min, select, undefined {} other {min. {min}}}{divider}{max, select, undefined {} other {max. {max}}}{unit}{br}{description}",
      "content-manager.form.Input.label": "برچسب",
      "content-manager.form.Input.label.inputDescription": "This value overrides the label displayed in the table's head",
      "content-manager.form.Input.pageEntries": "ورودی در هر صفحه",
      "content-manager.form.Input.pageEntries.inputDescription": "نکته: شما میتوانید این مورد را در بخش نوع مجموعه ها ویرایش کنید",
      "content-manager.form.Input.placeholder": "Placeholder",
      "content-manager.form.Input.placeholder.placeholder": "مقدار فوق العاده من",
      "content-manager.form.Input.search": "فعال سازی جستجو",
      "content-manager.form.Input.search.field": "فعال سازی جستجو در این بخش",
      "content-manager.form.Input.sort.field": "فعال کردن مرتب سازی در این بخش",
      "content-manager.form.Input.sort.order": "ترتیب مرتب سازی پیش فرض",
      "content-manager.form.Input.wysiwyg": "نمایش به صورت WYSIWYG",
      "content-manager.global.displayedFields": "بخش های نمایش داده شده",
      "content-manager.groups": "گروه ها",
      "content-manager.groups.numbered": "گروه ({number})",
      "content-manager.header.name": "محتوا",
      "content-manager.link-to-ctb": "ویرایش مدل",
      "content-manager.models": "اطلاعات پیاه",
      "content-manager.models.numbered": "اطلاعات پایه ({number})",
      "content-manager.notification.error.displayedFields": "حداقل به یک بخش نمایش داده شده نیاز دارید",
      "content-manager.notification.error.relationship.fetch": "مشکلی در هنگام دریافت رابطه پیش آمد",
      "content-manager.notification.info.SettingPage.disableSort": "شما باید یک ویژگی با مرتب سازی مجاز داشته باشید",
      "content-manager.notification.info.minimumFields": "باید حداقل یکی از بخش ها را نمایش دهید",
      "content-manager.notification.upload.error": "مشکلی در هنگام آپلود فایل ها پیش آمد",
      "content-manager.pageNotFound": "صفحه پیدا نشد",
      "content-manager.pages.ListView.header-subtitle": "{number, plural, =0 {# entries} one {# entry} other {# entries}} found",
      "content-manager.pages.NoContentType.button": "اولین نوع محتوای خود را بسازید",
      "content-manager.pages.NoContentType.text": "شما هنوز محتوایی ندارید، پیشنهاد میکنیم اولین نوع محتوای خود را بسازید",
      "content-manager.permissions.not-allowed.create": "شما اجازه ساخت این فایل را ندارید",
      "content-manager.permissions.not-allowed.update": "شما اجازه دیدن این فایل را ندارید",
      "content-manager.plugin.description.long": "روش سریع برای دیدن، ویرایش و حذف محتوا در دیتابیس",
      "content-manager.plugin.description.short": "روش سریع برای دیدن، ویرایش و حذف محتوا در دیتابیس",
      "content-manager.popUpWarning.bodyMessage.contentType.delete": "آیان از حذف این نوع محتوا اطمینان دارید؟",
      "content-manager.popUpWarning.bodyMessage.contentType.delete.all": "آیا از حذف این ورودی ها اطمینان دارید؟",
      "content-manager.popUpWarning.bodyMessage.contentType.publish.all": "آیا مطمئنید که می خواهید این ورودی ها را منتشر کنید؟",
      "content-manager.popUpWarning.bodyMessage.contentType.unpublish.all": "مطمئنید میخواید این ورودی را از خالت انتشار خارج کنید؟",
      "content-manager.popUpWarning.warning.has-draft-relations.title": "تاییدیه",
      "content-manager.popUpWarning.warning.publish-question": "هنوز میخواهید منتشر کنید؟",
      "content-manager.popUpWarning.warning.unpublish": "اگر این مطلب را منتشر نکنید، به صورت پیش فرض به پیش نویس تبدیل می شود",
      "content-manager.popUpWarning.warning.unpublish-question": "مطمئنید نمیخواهید این را منتشر کنید؟",
      "content-manager.popUpWarning.warning.updateAllSettings": "این تمام تنظیمات شما را تغییر می دهد",
      "content-manager.popUpwarning.warning.has-draft-relations.button-confirm": "بله، منتشر کن",
      "content-manager.popUpwarning.warning.has-draft-relations.message": "<b>{count, plural, one { relation is } other { relations are } }</b> not published yet and might lead to unexpected behavior.",
      "content-manager.popUpwarning.warning.bulk-has-draft-relations.message": "<b>{count} {count, plural, one { relation } other { relations } } out of {entities} { entities, plural, one { entry } other { entries } } {count, plural, one { is } other { are } }</b> not published yet and might lead to unexpected behavior. ",
      "content-manager.popover.display-relations.label": "غیر فعال سازی روابط",
      "content-manager.relation.add": "افزودن رابطه",
      "content-manager.relation.disconnect": "حذف",
      "content-manager.relation.isLoading": "در حال لود ارتباط ها",
      "content-manager.relation.loadMore": "لود بیشتر",
      "content-manager.relation.notAvailable": "ارتباطی وجود ندارد",
      "content-manager.relation.publicationState.draft": "پیش نویس",
      "content-manager.relation.publicationState.published": "منتشر شده",
      "content-manager.reviewWorkflows.stage.label": "بررسی مرحله",
      "content-manager.select.currently.selected": "{count} در حال حاظر انتخاب شده",
      "content-manager.success.record.delete": "حذف شد",
      "content-manager.success.record.publish": "منتشر شده",
      "content-manager.success.record.publishing": "در حال انتشار...",
      "content-manager.success.record.save": "ذخیره",
      "content-manager.success.record.unpublish": "انتشار نشده",
      "content-manager.utils.data-loaded": "{number, plural, =1 {entry has} other {entries have}}با موفقیت لود شد",
      "content-manager.listView.validation.errors.title": "عمل نیاز است",
      "content-manager.listView.validation.errors.message": "لطفا از صحت تمام بخش ها قبل از انتشار اطمینان حاصل کنید(required field, min/max character limit, etc.)",
      "dark": "تاریک",
      "form.button.continue": "ادامه",
      "form.button.done": "انجام شد",
      "global.actions": "Actions",
      "global.auditLogs": "گزارش های حسابرسی",
      "global.back": "برگشت",
      "global.cancel": "لغو",
      "global.change-password": "تغییر رمز",
      "global.close": "بستن",
      "global.content-manager": "مدیریت محتوا",
      "global.continue": "ادامه ",
      "global.delete": "حذف",
      "global.delete-target": "حذف {target}",
      "global.description": "توضیحات",
      "global.details": "جزئیات",
      "global.disabled": "غیر فعال",
      "global.documentation": "مستندات",
      "global.enabled": "فعال",
      "global.finish": "پایان",
      "global.marketplace": "مارکت",
      "global.name": "نام",
      "global.none": "هیچ کدام",
      "global.password": "رمز",
      "global.plugins": "پلاگین ها",
      "global.plugins.content-manager": "مدیریت محتوا",
      "global.plugins.content-manager.description": "راه سریع برای دیدن، ویرایش و حذف داده ها در دیتابیس",
      "global.plugins.content-type-builder": "سازنده نوع محتوا",
      "global.plugins.content-type-builder.description": "ساختار داده API خود را مدلسازی کنید. فقط در یک دقیقه زمینه ها و روابط جدید ایجاد کنید. فایل ها به طور خودکار در پروژه شما ایجاد و به روز می شوند.",
      "global.plugins.documentation": "مستندات",
      "global.plugins.documentation.description": "یک سند OpenAPI ایجاد کنید و API خود را با SWAGGER UI تجسم کنید.",
      "global.plugins.email": "ایمیل",
      "global.plugins.email.description": "برنامه خود را برای ارسال ایمیل پیکربندی کنید",
      "global.plugins.graphql": "GraphQL",
      "global.plugins.graphql.description": "نقطه پایانی GraphQL را با روش های پیش فرض API اضافه می کند.",
      "global.plugins.i18n": "بین المللی شدن",
      "global.plugins.i18n.description": "این افزونه امکان ایجاد، خواندن و به روز رسانی محتوا را به زبان های مختلف، هم از پنل مدیریت و هم از API می دهد..",
      "global.plugins.sentry": "نگهبان",
      "global.plugins.sentry.description": "ارسال اررور های استراپی به نگهبان",
      "global.plugins.upload": "کتابخانه رسانه ها",
      "global.plugins.upload.description": "مدیریت فایل های رسانه",
      "global.plugins.users-permissions": "نقش ها و اجازه ها",
      "global.plugins.users-permissions.description": "API خود را با یک فرآیند احراز هویت کامل بر اساس JWT محافظت کنید. این افزونه همچنین دارای یک استراتژی ACL است که به شما امکان می دهد مجوزها را بین گروه های کاربران مدیریت کنید.",
      "global.profile": "پروفایل",
      "global.prompt.unsaved": "مطمئنید میخواهید این صفحه را ترک کنید؟ همه تغییرات شما از دست می رود",
      "global.reset-password": "بازیابی رمز",
      "global.roles": "نقش ها",
      "global.save": "ذخیره",
      "global.search": "جست و جو",
      "global.see-more": "بیشتر",
      "global.select": "انتخاب",
      "global.select-all-entries": "انتخاب تمام ورودی ها",
      "global.settings": "تنظیمات",
      "global.type": "مدل",
      "global.users": "کاربران",
      "global.fullname": "{firstname} {lastname}",
      "light": "روشن",
      "notification.contentType.relations.conflict": "نوع محتوا روابط متناقضی دارد",
      "notification.default.title": "اطلاعات:",
      "notification.ee.warning.at-seat-limit.title": "{licenseLimitStatus, select, OVER_LIMIT {Over} AT_LIMIT {At}} seat limit ({currentUserCount}/{permittedSeats})",
      "notification.ee.warning.over-.message": "افزودن صندلی به  {licenseLimitStatus, select, OVER_LIMIT {invite} AT_LIMIT {re-enable}} Users. If you already did it but it's not reflected in Strapi yet, make sure to restart your app.",
      "notification.error": "اروری پیش آمد",
      "notification.error.invalid.configuration": "شما یک پیکربندی نامعتبر دارید، برای اطلاعات بیشتر گزارش سرور خود را بررسی کنید.",
      "notification.error.layout": "طرح بندی بازیابی نشد",
      "notification.error.tokennamenotunique": "این نام  قبلا به توکن دیگری اختصاص داده شده است",
      "notification.form.error.fields": "این فرد دارای چند اررور است",
      "notification.form.success.fields": "تغییرات ذخیره شد",
      "notification.link-copied": "لینک در کیبرد کپی شد",
      "notification.permission.not-allowed-read": "شما اجازه دیدن این فایل را ندارید",
      "notification.success.apitokencreated": "توکن API با موفقیت ساخته شد",
      "notification.success.apitokenedited": "توکن API با موفقیت ویرایش شد",
      "notification.success.delete": "این ایتم حذف شده است",
      "notification.success.saved": "ذخیره شد",
      "notification.success.title": "موفقیت:",
      "notification.success.transfertokencreated": "توکن انتقال با موفقیت ایجا شد",
      "notification.success.transfertokenedited": "توکن انتقال با موفقیت ویرایش شد",
      "notification.version.update.message": "ورژن جدید استراپی در دسترس است",
      "notification.warning.404": "404 - پیدا نشد",
      "notification.warning.title": "اخطار:",
      "or": "یا",
      "request.error.model.unknown": "این مدل وجود ندارد",
      "selectButtonTitle": "انتخاب",
      "skipToContent": "پرش به محتوا",
      "submit": "ارسال"
    },


  }
};

const bootstrap = (app) => {

  // try {

  //   axios.post("http://localhost:5000/login", {
  //     username: "admin",
  //     password: "@nis@1400"
  //   },{
  //     withCredentials:true
  //   }).then(responses=>{
  //     console.log("then=>responses.data=>",responses.data)
  //   }).catch(reason => {
  //       console.log("reason=>",reason)
  //     }
  //   )
  //
  // } catch (e) {
  //   console.log(e)
  // }


  console.log(app);
};

export default {
  config,
  bootstrap,
};
